### ISSUE TITLE
jiekouAD 导致图床上传时不显示按钮

### ISSUE THREAD

**Issue by 7peanuts** [damengzhu/banad#44]
这两个图床，还有类似这俩的图床，上传按钮都不显示了，关闭后正常显示
https://im.ge/upload
https://imgbb.com/
![20230213201226](https://user-images.githubusercontent.com/82173614/218454818-ffa1c0d6-fe5f-46bd-bd6e-b84a367df513.jpg)

**Comment by damengzhu** [comment]
你看看拦截日志是哪条规则，我用的手机

**Comment by 7peanuts** [comment]
拦截记录从哪看呢

**Comment by damengzhu** [comment]
![Screenshot_20230213202402](https://user-images.githubusercontent.com/80020206/218456818-03de984a-26c8-40b8-8724-58d0655a7ec0.png)
这里

**Comment by 7peanuts** [comment]
<details><summary>Logger output</summary>

```
+3
im.ge
1
image
https://im.ge/content/images/system/favicon_1622482133743_ac8bd9.png
```
```
+3
im.ge
1
image
https://im.ge/content/images/system/favicon_1622482133743_ac8bd9.png
```
```
+3
##div[id*="ad"][class*="text"]
im.ge
dom
https://im.ge/upload
```
```
+2
||googletagmanager.com^
--
im.ge
3
script
https://www.googletagmanager.com/gtag/js?id=UA-198341460-1
```
```
+1
im.ge
1
css
https://im.ge/lib/Peafowl/font-awesome-5/css/all.min.css?98dfc2877c9a29f77b733eb45a945358
```
```
+1
im.ge
1
css
https://im.ge/app/themes/Peafowl/style.min.css?98dfc2877c9a29f77b733eb45a945358
```
```
+1
im.ge
1
css
https://im.ge/lib/Peafowl/peafowl.min.css?98dfc2877c9a29f77b733eb45a945358
```
```
+0
im.ge
1
doc
https://im.ge/upload
```
```
+0
https://im.ge/upload
```
</details>

![20230213202805](https://user-images.githubusercontent.com/82173614/218458165-e7d586fe-2da2-42fa-9c68-1702490b5052.jpg)

**Comment by damengzhu** [comment]
更新了，如果github有缓存延迟可以用GitLink 镜像

**Comment by 7peanuts** [comment]
> 更新了，如果github有缓存延迟可以用GitLink 镜像

感谢，可以了！
