### ISSUE TITLE
#5188行导致谷歌搜索内容的icon不显示

### ISSUE THREAD

**Issue by psychosispy** [damengzhu/banad#48]
##[src^='data:image/png;base64,iVBORw0KGgoAAAANSU'][style*='position: fixed; z-index: 2000000000; width: 30px; bottom:']

**Comment by damengzhu** [comment]
![Screenshot_2024-03-25-08-14-24-620_com mmbox xbrowser](https://github.com/damengzhu/banad/assets/80020206/1a04298e-aa78-4cfe-af57-dfb12f2f0853)
试了没问题啊

**Comment by damengzhu** [comment]
![Screenshot_2024-03-25-08-45-59-464_com mmbox xbrowser](https://github.com/damengzhu/banad/assets/80020206/79bf46e0-8480-46a6-9aa0-d8c6390081fe)
style元素都不一样，你用啥拦截的？
