### ISSUE TITLE
hentaicomic.ru 

### ISSUE THREAD

**Issue by Aloazny** [damengzhu/banad#50]
> 网站 [hentaicomic.ru](https://hentaicomic.ru) 
  - 误杀漫画下载按钮，无法下载漫画

**Comment by damengzhu** [comment]
你搞错规则了，不是我规则误杀

**Comment by Aloazny** [comment]
[ABP Merge Rules](https://raw.githubusercontent.com/damengzhu/abpmerge/main/abpmerge.txt) 不也是您的吗？

**Comment by Aloazny** [comment]
我想着ABP Merge Rules上游也是您，所以直接反馈了到轻量规则了😂。

**Comment by damengzhu** [comment]
更新了，要订阅轻量规则，ABP Merge Rules还没同步

**Comment by Aloazny** [comment]
> 更新了，要订阅轻量规则，ABP Merge Rules还没同步

OK，感谢大佬！
