### ISSUE TITLE
https://ciliyinqing.top/

### ISSUE THREAD

**Issue by Aloazny** [damengzhu/banad#53]
> #误杀

大佬，误杀了一个网站，[磁力引擎](https://ciliyinqing.top/)
![Screenshot_2024-10-02-17-05-45-790_mark.via.gp.jpg](https://github.com/user-attachments/assets/a55d6c1d-b716-4a0f-9ef4-0edbe6a4c568)

误杀的规则好像是这个
```
||ciliyinqing.top^
```

**Comment by damengzhu** [comment]
更新了

**Comment by Aloazny** [comment]
> 更新了

好的，辛苦大佬了！
