### ISSUE TITLE
Invalid Entries in jiekouAD.txt's Domain Block Rules

### ISSUE THREAD

**Issue by sr093906** [damengzhu/banad#7]
These 140 or so domains are either unregistered or expired one month or more ago.

|domain|registered|status|expires|
|:--|:--|:--|:--|
|ssh.vtfwgfo.cn|no|-|-|
|www.zopeynxv.top|no|-|-|
|show.13wnjs.com|no|-|-|
|ssh.iwwacgx.cn|no|-|-|
|med.fxfvttu.cn|no|-|-|
|xg.depnegj.cn|no|-|-|
|mimg.hjmoiye.cn|no|-|-|
|ximg.wkvxuoi.cn|no|-|-|
|appid.ebrhnud.cn|no|-|-|
|mg.ipdxwtn.cn|no|-|-|
|pic.rliolmx.cn|no|-|-|
|mc.uiqjcpt.cn|no|-|-|
|ssh.xnmcmnt.cn|no|-|-|
|ssh.ru32an.cn|no|-|-|
|ssh.njcyfpv.cn|no|-|-|
|xg.tjwmtrw.cn|no|-|-|
|xc.xiyqjea.cn|no|-|-|
|vegoid.cn|no|-|-|
|xn--2qux23c9ziyrq.site|no|-|-|
|jy0d.batgmxg.cn|no|-|-|
|pcouis.cn|no|-|-|
|jfsdiwmnbsk011.top|no|-|-|
|wabizc.cn|no|-|-|
|xn--2qux23c9ziyrq.club|no|-|-|
|vdcfes.cn|no|-|-|
|siwakong.cc|no|-|-|
|xl.msspgw.cn|no|-|-|
|ssh.egesckx.cn|no|-|-|
|sivide.cn|no|-|-|
|xg.zhlzdhr.cn|no|-|-|
|xl.llrnlzl.cn|no|-|-|
|mg.btnvlvt.cn|no|-|-|
|xg.whsbpw.cn|no|-|-|
|exh.xuhuihui.top|no|-|-|
|www.poakdv.cn|no|-|-|
|xn--2qu92fhtx4ff.club|no|-|-|
|eec.sachbs.club|no|-|-|
|www.tx058.com|no|-|-|
|m2.xycnzz.com|no|-|-|
|wsvike.cn|no|-|-|
|sxh.xuhuihui.top|no|-|-|
|xn--2qu92fhtx4ff.site|no|-|-|
|hcprzx.cn|no|-|-|
|ssh.wbdcrmn.cn|no|-|-|
|t.pd74.top|no|-|-|
|api.dunhee.cn|no|-|-|
|www.66994.top|no|-|-|
|tz.obboob.cn|no|-|-|
|m.xingyaoapi.com|no|-|-|
|www.jcdfdhx.top|no|-|-|
|y76.ylems.club|no|-|-|
|www.hjkl888.com|no|-|-|
|www.vivituii.com|no|-|-|
|s.shaowenhao.top|no|-|-|
|y90.zdmzhzu.cn|no|-|-|
|www.wacc888.com|no|-|-|
|www.hh12345.xyz|no|-|-|
|bnetds.cn|no|-|-|
|elsalaes.com|no|-|-|
|ssh.cralp.cn|no|-|-|
|s1.ei16h.cn|no|-|-|
|xz.xliansheng.com|no|-|-|
|iodu.iiasyba.cn|no|-|-|
|m.nxwzfz.com|no|-|-|
|d.yyjsbz.cn|no|-|-|
|m.xqxx520.com|no|-|-|
|mvo.bsadfs.xyz|no|-|-|
|eo.sdakxz.xyz|no|-|-|
|eo.zzbya.xyz|no|-|-|
|www.wowoyy.cc|no|-|-|
|m.sinostoneauction.cn|no|-|-|
|www.baidumanager.club|yes|-|-|
|eco.4hs345.xyz|no|-|-|
|hfjdhow888.aikantxt.la|yes|-|-|
|jltoyou.com|no|-|-|
|mvo.dfger.xyz|no|-|-|
|m.29hgg.cn|no|-|-|
|m.zgwlbjy.cn|no|-|-|
|m.congcuitang.cn|no|-|-|
|m.yujianai520.com|no|-|-|
|m.36ia2.cn|no|-|-|
|m.yljmeishi.cn|no|-|-|
|m.nanjingmeitian.cn|no|-|-|
|eo.sdadxz.xyz|no|-|-|
|ay.3lga3.cn|no|-|-|
|l2.kouwku.cn|no|-|-|
|njx.0302woeuxcbrnxcvsdfghu.xyz|no|-|-|
|yihuayiyong.cn|no|-|-|
|res.haomaojin888.com|no|-|-|
|acoxcv.cn|no|-|-|
|xl.xg978.cn|no|-|-|
|m.arxnfj14120.cn|no|-|-|
|m.5rxk.cn|no|-|-|
|pyzhtj.com|no|-|-|
|easypatent.net|no|-|-|
|f.x91n4a.com|no|-|-|
|czk.gemeiyun.com|yes|clientTransferProhibited<br/>pendingDelete|2021-02-25|
|www.xn--wcsy74a6d835f5lf.com|yes|pendingDelete|2021-02-28|
|s.uidcn.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>pendingDelete|2021-03-08|
|s.xiiiwm.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>pendingDelete|2021-03-09|
|wgf.ioahdio.com|yes|clientTransferProhibited<br/>pendingDelete|2021-03-11|
|www.abie10.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-03-13|
|www.d8ekco.com|yes|clientTransferProhibited<br/>redemptionPeriod|2021-03-15|
|t.oohxa.xyz|yes|pendingDelete<br/>serverHold<br/>serverTransferProhibited<br/>clientTransferProhibited<br/>redemptionPeriod|2021-03-15|
|www.oiwjcsh012.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-03-16|
|www.oiwjcsh013.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-03-16|
|www.oiwjcsh014.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-03-16|
|www.oiwjcsh015.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-03-16|
|www.oiwjcsh016.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-03-16|
|www.oiwjcsh017.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-03-16|
|www.oiwjcsh018.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-03-16|
|www.oiwjcsh019.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-03-16|
|www.oiwjcsh020.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-03-16|
|www.oiwjcsh011.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-03-16|
|www.oiwjcsh010.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-03-16|
|www.oiwjcsh001.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-03-16|
|epp.2polj.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-03-21|
|www.tctakoh.com|yes|REDEMPTIONPERIOD<br/>redemptionPeriod|2021-03-21|
|nike666.com|yes|redemptionPeriod|2021-03-25|
|udryl.hyyazhaji.com|yes|ok|2021-03-30|
|vj.tianji520.cn|yes|pendingDelete<br/>inactive|2021-03-31|
|api.lwansc.cn|yes|pendingDelete<br/>clientTransferProhibited<br/>inactive|2021-04-01|
|eqq.damumu.xyz|yes|pendingDelete<br/>serverHold<br/>serverTransferProhibited<br/>clientHold<br/>clientTransferProhibited<br/>redemptionPeriod|2021-04-02|
|api.szmhxx.cn|yes|pendingDelete<br/>inactive|2021-04-04|
|www.abie26.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-04-07|
|www.abie23.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-04-07|
|www.abie25.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-04-07|
|www.abie18.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-04-07|
|www.abie15.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-04-07|
|www.abie16.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-04-07|
|js.qsk666.com|yes|clientTransferProhibited<br/>redemptionPeriod|2021-04-07|
|www.abie14.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-04-07|
|abie12.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-04-07|
|www.abie19.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-04-07|
|www.abie20.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-04-07|
|www.abie21.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-04-07|
|www.abie22.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-04-07|
|www.abie24.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-04-07|
|www.5zi3.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-04-09|
|www.5zi2.top|yes|clientUpdateProhibited<br/>pendingDelete<br/>redemptionPeriod|2021-04-09|
|eeg.gmuqa.cn|yes|pendingDelete<br/>inactive|2021-04-13|
|cdn.jiujhzp.com|yes|ok|2021-04-15|
|i8.i8ggwm.com|yes|clientTransferProhibited<br/>clientUpdateProhibited<br/>clientRenewProhibited<br/>clientDeleteProhibited|2021-04-21|
|code.hnxcdjk.com|yes|clientTransferProhibited|2021-04-23|
|517heiya.com|yes|clientTransferProhibited|2021-04-25|

**Comment by sr093906** [comment]
Full whois records for the domains.
[damengzhu.xlsx](https://github.com/damengzhu/banad/files/6491022/damengzhu.xlsx)

**Comment by damengzhu** [comment]
我不懂怎么去除，你可以帮忙去除后把文件发我吗？
I don't know how to remove it. Can you help me remove it and send me the file?

**Comment by sr093906** [comment]
The simplest way is to remove manually. It is not a high-tech task but takes time.

**Comment by damengzhu** [comment]
The invalid domain name has been deleted

**Comment by damengzhu** [comment]
Invalid domain name has been deleted
