### ISSUE TITLE
Inactive Domains

### ISSUE THREAD

**Issue by sr093906** [damengzhu/banad#9]
No DNS record for the following domains. 

a.shandiankami.cn
aaa.3hgui.com
abie12.top
ad.hieahgkcha.cn
aixixi668.2txt.cc
alibu.2526game.com
ap.hsyjxzl.cn
api.dedayuntong.com
api.jcswhg.com
api.nuanyanghb.com
aq.hieahgkcha.cn
aqllq.993726.cn
b1c2d3.cfff.ne
b2.ai5z.com
baiducdn.9wlm.com
c1.m.ifeng.com
c.dzuky.top
c.njcyt.com
c.tjmzzk.com
c.wangdaguanli.com
c.yanyanbiji.com
cdn2.071811.cc
cdn.jiujhzp.com
cdn.m.baidu.com.www-sina-cn-com.com
ck.foxyier.xyz
code.hnxcdjk.com
czk.gemeiyun.com
d.haireig.com
d.jutaowanggou.cn
d.lionettrip.xyz
danlidanli.ne
data.hhhhbf.com
di.fengchedaomall.cn
dn.znxblom.cn
dserver.juicyads.com
dx.dihuizs.cn
eca.caredaily.me
ect.geileba.cn
eeg.gmuqa.cn
enw.nwpuis.top
eo.bigcooe.xyz
ex.xuzewu.me
f.babayboy.com
f.ustclsy.com
fa.sdxctr.com
fw.privateadx.com
g9.o24eq.cn
g.aisouk.cn
gg.wjaa23.com
h.xjhjtz.cn
hf.94dayu.com
hfjdhow888.aikantxt.la
html.zp0737.com
i8.i8ggwm.com
iky.sinabuy.cn
img.hdsygw.cn
img.imagecdn.cn
img.jjkaifa.com
in.indiebuff.cn
in.taomochou.cn
iz8c7j.0mr.cc
j.qzxmtyy.com
jc.vtqifk86868.cn
jd.jxmzyg.com
jd.zxsmxt.com
jhsyt.dtletao.com
jkjei8.cn
js.51toubu.com
js.99tianxin.com
js.abchinajn.com
js.handanxinkai.com
js.hldslgg.com
js.huanning.top
js.kuxinqi.com
js.maidagu.com
js.qudaoweiwang.com
js.xcmz999.com
js.xihuangdushu.com
jxwef0.cn
k.ailefen.com
k.cnsayo.com
k.jjhaolin.com
k.qsbxg2.com
kc.jjhaolin.com
kl.jjhaolin.com
l1.5fh44.cn
l.dzooo.cn
l.reendian.cn
lq0s3c.cn
ls9x.pk965.com
lyz.radio366.com
m.8c3k.cn
m.am77p.cn
m.cqhengnuo.cn
m.czhywzhsyxgs.com
m.globbiz.cn
m.julitenj.com
m.niutaizong.cn
m.nlyjs2015.com
m.nmzqhx.com
m.qlssbq.cn
m.rzxlszy.vip
m.yapusheji.com
m.zrmxswrl.com
mao.onesg.cn
mo.bigcoob.xyz
mo.bigcooc.xyz
mo.bigcooe.xyz
mp.qy9.net
news.xcmz999.com
otf.mangqu.cn
q25qlf.cn
qvwa7.xxllz.top
qyky.6wads.com
run.haireig.com
s.aiba5.xyz
s.alightin.com
s.jjcclc.top
s.mankegst.shop
sdk.nouzhu.cn
show.adiniky.com
ssy.syzzhd.cn
statics.8nx7hlj.cn
sv7oqa.cn
sxc.xmrzw.cn
szb.tongpinw.com
t.jjjdjc.top
t.nijiua.com
t.zzwflxs.com
tld.kaixintou8.com
todays.wa11ace.net
udryl.hyyazhaji.com
um.tltwcn.com
uoss.hm757.cn
uu.jiudiandyw.com
v6.klmc88.cn
v.njcyt.com
v.shangyingwm.com
v.shwebi.cn
v.wangdaguanli.com
v.yanyanbiji.com
vip.adinisp.com
vip.jiangrenzhiguo.com
vj.quanjingpay.com
vpn.ch-hr12333.com
vpn.youyisheng.net
wanpaig.4567.org
www.5zi2.top
www.5zi3.top
www.56space.com
www.66993.top
www.abie14.top
www.abie19.top
www.abie20.top
www.abie21.top
www.abie22.top
www.abie24.top
www.aotetu.cn
www.aoyinn.com
www.d8ekco.com
www.ffa9.cn
www.fjsjsj.com
www.fzdeng.com
www.gralfusnzpo003.top
www.gralfusnzpo004.top
www.gralfusnzpo005.top
www.gralfusnzpo006.top
www.gralfusnzpo007.top
www.gralfusnzpo008.top
www.gralfusnzpo009.top
www.jfsdiwmnbsk002.top
www.jfsdiwmnbsk003.top
www.jfsdiwmnbsk004.top
www.jfsdiwmnbsk005.top
www.jfsdiwmnbsk006.top
www.jfsdiwmnbsk007.top
www.ningxiayy.com
www.qtlianmeng.com
www.ranqibio.com
www.snapptrader.com
www.yhhls.com
www.zvnjghj.com
wxw.zhongdoulicai.com
xdm.bozhixiang.top
xl.2dl1w.cn
xn--2qu92fhtx4ff.ink
xn--2qu92fhtx4ff.ren
xn--2qu92fhtx4ff.video
xn--2qux23c9ziyrq.icu
xn--2qux23c9ziyrq.ink
xn--2qux23c9ziyrq.video
xn--2quz8f01ak10c.shop
xn--i7qt52bvsr0u0a.cc
xxl.94dayu.com
yndication.exosrv.com
ys.czxnub.top
z.zhizones.com
1pzskg.cn
9vyr.beianmrc.cn
56.xxdongfa.com
83.hyjzsj.cn
83.shandiankami.cn
145.shandiankami.cn
8292918saturday.sgbbc.cn

**Comment by damengzhu** [comment]
> 以下域没有 DNS 记录。
> 
> a.shandiankami.cn
> aaa.3hgui.com
> abie12.top
> ad.hieahgkcha.cn
> aixixi668.2txt.cc
> alibu.2526game.com
> ap.hsyjxzl.cn
> api.dedayuntong.com
> api.jcswhg.com
> api.nuanyanghb.com
> 水性。 hieahgkcha.cn
> aqllq.993726.cn
> b1c2d3.cfff.ne
> b2.ai5z.com
> baiducdn.9wlm.com
> c1.m.ifeng.com
> c.dzuky.top
> c.njcyt.com
> c.tjmzzk.com
> c.wangdaguanli.com
> c.yanyanbiji.com
> cdn2.071811.cc
> cdn.jiujhzp.com
> cdn.m.baidu.com.www-sina-cn-com.com
> ck.foxyier.xyz
> code.hnxcdjk.com
> czk.gemeiyun.com
> d.haireig .com
> d.聚淘网购.cn
> d.lionettrip.xyz danlidanli.ne
> data.hhhhbf.com
> di.fengchedaomall.cn
> dn.znxblom.cn
> dserver.juicyads.com
> dx.dihuizs.cn
> eca.caredaily.me
> ect.geileba.cn
> eeg.gmuqa.cn
> enw
> . nwpuis.top
> eo.bigcooe.xyz
> ex.xuzewu.me
> f.babayboy.com
> f.ustclsy.com
> fa.sdxctr.com
> fw.privateadx.com
> g9.o24eq.cn
> g.aisouk.cn
> gg.wjaa23.com
> h. xjhjtz.cn
> hf.94dayu.com
> hfjdhow888.aikantxt.la
> html.zp0737.com
> i8.i8ggwm.com
> iky.sinabuy.cn
> img.hdsygw.cn
> img.imagecdn.cn
> img.jjkaifa.com
> in.indiebuff.cn
> in.taomochou.cn
> iz8c7j.0mr.cc
> j.qzxmtyy.com
> jc.vtqifk86868.cn
> jd.jxmzyg.com
> jd.zxsmxt.com
> jhsyt.dtletao.com
> jkjei8.cn
> js.51toubu.com
> js.99tianxin.com
> JS。 abchinajn.com
> js.handanxinkai.com
> js.hldslgg.com
> js.huanning.top
> js.kuxinqi.com
> js.maidagu.com
> js.qudaoweiwang.com
> js.xcmz999.com
> js.xihuangdushu.com
> jxwef0.cn
> k.ailefen. com
> k.cnsayo.com
> k.jjhaolin.com
> k.qsbxg2.com
> kc.jjhaolin.com
> kl.jjhaolin.com
> l1.5fh44.cn
> l.dzooo.cn
> l.reendian.cn
> lq0s3c.cn
> ls9x.pk965.com
> lyz.radio366.com
> m.8c3k.cn
> m.am77p.cn
> m.cqhengnuo.cn
> m.czhywzhsyxgs.com
> m.globbiz.cn
> m.julitenj.com
> m.niutaizong.cn
> m.nlyjs2015.com
> m.nmzqhx.com
> m.qlssbq.cn
> m.rzxlszy.vip
> m.yapusheji.com
> m.zrmxswrl.com
> mao.onesg.cn
> mo.bigcoob.xyz
> mo.bigcooc.xyz
> mo.bigcooe.xyz
> mp.q​​y9.net
> news.xcmz999.com
> otf.mangqu.cn
> q25qlf.cn
> qvwa7.xxllz.top
> qyky.6wads.com
> run.haireig.com
> s.aiba5.xyz
> s.alightin.com
> s.jjcclc.top
> s.mankegst.shop
> sdk.牛猪网
> show.adiniky.com
> ssy.syzzhd.cn
> statics.8nx7hlj.cn
> sv7oqa.cn
> sxc.xmrzw.cn
> szb.tongpinw.com
> t.jjjdjc.top
> t.nijiua.com
> t.zzwflxs.com
> tld.kaixintou8.com
> 今天。 wa11ace.net
> udryl.hyyazhaji.com
> um.tltwcn.com
> uoss.hm757.cn
> uu.jiudiandyw.com
> v6.klmc88.cn
> v.njcyt.com
> v.shangyingwm.com
> v.shwebi.cn
> v.wangdaguanli.com
> v. yanyanbiji.com
> vip.adinisp.com
> vip.jiangrenzhiguo.com
> vj.quanjingpay.com
> vpn.ch-hr12333.com
> vpn.youyisheng.net
> wanpaig.4567.org
> [www.5zi2.top ](http://www.5zi2.top)
> [www.5zi3.top](http://www.5zi3.top)
> [www.56space.com ](http://www.56space.com)
> [www.66993.top ](http://www.66993.top)
> [www.abie14.top ](http://www.abie14.top)
> [www.abie19.top ](http://www.abie19.top)
> [www.abie20.top ](http://www.abie20.top)
> [www.abie21.top ](http://www.abie21.top)
> [www.abie22.top ](http://www.abie22.top)
> [www.abie24.top ](http://www.abie24.top)
> [www.aotetu.cn ](http://www.aotetu.cn)
> [www.aoyinn.com ](http://www.aoyinn.com)
> [www.d8ekco.com ](http://www.d8ekco.com)
> [www.ffa9.cn ](http://www.ffa9.cn)
> [www.fjsjsj.com ](http://www.fjsjsj.com)
> [www.fzdeng.com ](http://www.fzdeng.com)
> [www.gralfusnzpo003.top ](http://www.gralfusnzpo003.top)
> [www.gralfusnzpo004.top ](http://www.gralfusnzpo004.top)
> [www.gralfusnzpo005.top ](http://www.gralfusnzpo005.top)
> [www.gralfusnzpo006.top ](http://www.gralfusnzpo006.top)
> [www.gralfusnzpo007.nztop ](http://www.gralfusnzpo007.top)
> [www.gralfus ](http://www.gralfusnzpo008.top)
> [www.gralfusnzpo009.top ](http://www.gralfusnzpo009.top)
> [www.jfsdiwmnbsk002.top ](http://www.jfsdiwmnbsk002.top)
> [www.jfsdiwmnbsk003.top ](http://www.jfsdiwmnbsk003.top)
> [www.jfsdiwmnbsk004.top ](http://www.jfsdiwmnbsk004.top)
> [www.jfsdiwmnbsk005.top ](http://www.jfsdiwmnbsk005.top)
> [www.jfsdiwmnbsk006.top ](http://www.jfsdiwmnbsk006.top)
> [www.jfsdiwmnbsk007.top ](http://www.jfsdiwmnbsk007.top)
> [www.ningxiayy.com](http://www.ningxiayy.com)
> [www.qtlianmeng.com ](http://www.qtlianmeng.com)
> [www.ranqibio.com ](http://www.ranqibio.com)
> [www.snapptrader.com ](http://www.snapptrader.com)
> [www.yhhls.com ](http://www.yhhls.com)
> [www.zvnjghj.com](http://www.zvnjghj.com)
> wxw.zhongdoulicai.com
> xdm.bozhixiang.top
> xl.2dl1w.cn
> xn--2qu92fhtx4ff.ink
> xn-2qux9fh .ren
> xn--2qu92fhtx4ff.video
> xn--2qux23c9ziyrq.icu
> xn--2qux23c9ziyrq.ink
> xn--2qux23c9ziyrq.video
> xn--2quz8f01ak10c.shop
> xn--i7qt52bvsr0u0a.cc
> xxl.94dayu.com
> yndication.exosrv.com
> YS。 czxnub.top
> z.zhizones.com
> 1pzskg.cn
> 9vyr.beianmrc.cn
> 56.xxdongfa.com
> 83.hyjzsj.cn
> 83.shandiankami.cn
> 145.shandiankami.cn
> 8292918saturday.sgbbc.cn

**Comment by damengzhu** [comment]
Inactive Domain deleted😁

**Comment by sr093906** [comment]
Thanks.
